architecture:
  arch_type: "HarDNetDFUS"
  model_name: "HarDNetDFUS-R-KvasirCVC"
  in_size: 384
  multiscale:
    multiscale_factor: 0.25
    divisor: 64
    align_corners: False
settings:
  max_epochs: 300
  batch_size: 6
  random_seed: 42
  full_determinism: False
  mixed_precision: True
  torch_compile: False
  num_workers: 4
  pin_memory: True
  checkpoints:
    save_mode: 'best_and_last'
    metric: "iou"
    min_epoch: 50
  save_sample_segmentations: False
  transforms_backend: "albumentations"
optimizer:
  type: "AdamW"
  lr: 0.0001
loss:
  type: "default"
scheduler:
  type: "cosine_annealing"
  T_max: 300
  verbose: True
early_stop: False
metrics:
  tracked:
    - "dice"
    - "iou"
    - "precision"
    - "recall"
  averaging_method: "micro"
  ignore_background_class: True
dataset: # Polyp-Quintet configuration
  type: "KvasirCVCTrain"
  aux_test_datasets:
    - "CVCClinicDbTest"
    - "KvasirSegTest"
    - "CVC300Test"
    - "CVCColonDbTest"
    - "EtisLaribPolypDbTest"
transforms:
  train:
    - square_pad:
        value: 0
        mask_value: 0
    - one_of:
        - center_crop:
            height: 384
            width: 384
            p: 0.5
        - random_crop:
            height: 384
            width: 384
            p: 0.5
        - p: 1
    - shift_scale_rotate:
        shift_limit: 0.1
        scale_limit: 0.1
        rotate_limit: 45
        p: 0.5
    - one_of:
        - coarse_dropout:
            max_holes: 8
            max_height: 20
            max_width: 20
            min_width: 8
            fill_value: 0
            P: 1
        - gauss_noise:
            var_limit: (10.0, 50.0)
            mean: 0
            P: 1
        - p: 0.5
    - normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    - to_tensor: True
  test:
    - resize:
        height: 384
        width: 384
    - normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    - to_tensor: True
