architecture:
  arch_type: "SegformerB3"
  model_name: "SegformerB3-R-CFU-512-STUDY-BEST"
  in_size: 512
  num_heads: (1, 2, 5, 8)
  encoder_drop_rate: 0.0
  mlp_embed_dim: 768
  decoder_drop_rate: 0.0

settings:
  max_epochs: 256
  batch_size: 6
  random_seed: 9015964
  full_determinism: False
  mixed_precision: True
  torch_compile: False
  num_workers: 4
  pin_memory: True
  checkpoints:
    save_mode: "best_and_last"
    metric: "iou"
    min_epoch: 0
  eval_object_sizes: True
  save_sample_segmentations: True
  transforms_backend: "torchvision"

optimizer:
  type: "AdamW"
  lr: 0.00001
  weight_decay: 0.01

loss:
  type: "BCEL"

scheduler:
  type: "REX"
  T_max: 256

early_stop: False

metrics:
  tracked:
    - "dice"
    - "iou"
    - "precision"
    - "recall"
    - "f1_score"
  averaging_method: "micro"
  ignore_background_class: True

dataset:
  type: "CFU"

transforms:
  train:
    - to_tensor: True
    - pad_and_resize:
        size: 512
    - gaussian_blur:
        kernel_size: 25
        sigma: (0.001, 2.0)
    - random_affine:
        degrees: (-180, 180)
        translate: (0.25, 0.25)
        scale: (0.75, 1.25)
        shear: 17.5
        fill: 0
        mask_fill: 0
    - threshold:
        threshold: 127
        pixel_min: 0
        pixel_max: 255
        apply_to_mask: True
        apply_to_image: False
    - random_photometric_distort:
        brightness: (0.875, 1.125)
        contrast: (0.5, 1.5)
        saturation: (0.5, 1.5)
        hue: (-0.05, 0.05)
        p: 0.5
    - random_horizontal_flip:
        p: 0.5
    - random_vertical_flip:
        p: 0.5
    - normalize:
        mean: [ 0.5, 0.5, 0.5 ]
        std: [ 0.5, 0.5, 0.5 ]
        apply_to_mask: False

  val:
    - to_tensor: True
    - pad_and_resize:
        size: 512
    - threshold:
        threshold: 127
        pixel_min: 0
        pixel_max: 255
        apply_to_mask: True
        apply_to_image: False
    - normalize:
        mean: [ 0.5, 0.5, 0.5 ]
        std: [ 0.5, 0.5, 0.5 ]
        apply_to_mask: False

  test:
    - to_tensor: True
    - pad_and_resize:
        size: 512
    - threshold:
        threshold: 127
        pixel_min: 0
        pixel_max: 255
        apply_to_mask: True
        apply_to_image: False
    - normalize:
        mean: [ 0.5, 0.5, 0.5 ]
        std: [ 0.5, 0.5, 0.5 ]
        apply_to_mask: False
